/**
 * Inventory domain — product and stock business operations.
 *
 * Direct Prisma calls, flat async functions, no class wrappers.
 */
import { Decimal } from "@prisma/client/runtime/library";
export declare function getProductById(id: string): Promise<{
    tenantId: string;
    id: string;
    name: string;
    tags: string[];
    createdBy: string | null;
    updatedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    cess: Decimal;
    description: string | null;
    category: string;
    unit: string;
    mrp: Decimal | null;
    hsnCode: string | null;
    gstRate: Decimal;
    subCategory: string | null;
    sku: string | null;
    barcode: string | null;
    price: Decimal;
    cost: Decimal | null;
    wholesalePrice: Decimal | null;
    priceTier2: Decimal | null;
    priceTier3: Decimal | null;
    baseUnit: string | null;
    baseUnitQuantity: Decimal | null;
    stock: number;
    minStock: number;
    maxStock: number | null;
    location: string | null;
    isGstExempt: boolean;
    trackBatches: boolean;
    trackSerialNumbers: boolean;
    hasVariants: boolean;
    imageUrl: string | null;
    imageUrls: string[];
    preferredSupplier: string | null;
    supplierId: string | null;
    isActive: boolean;
    isFeatured: boolean;
    attributes: import("@prisma/client/runtime/library").JsonValue;
} | null>;
export declare function searchProducts(query: string): Promise<{
    tenantId: string;
    id: string;
    name: string;
    tags: string[];
    createdBy: string | null;
    updatedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    cess: Decimal;
    description: string | null;
    category: string;
    unit: string;
    mrp: Decimal | null;
    hsnCode: string | null;
    gstRate: Decimal;
    subCategory: string | null;
    sku: string | null;
    barcode: string | null;
    price: Decimal;
    cost: Decimal | null;
    wholesalePrice: Decimal | null;
    priceTier2: Decimal | null;
    priceTier3: Decimal | null;
    baseUnit: string | null;
    baseUnitQuantity: Decimal | null;
    stock: number;
    minStock: number;
    maxStock: number | null;
    location: string | null;
    isGstExempt: boolean;
    trackBatches: boolean;
    trackSerialNumbers: boolean;
    hasVariants: boolean;
    imageUrl: string | null;
    imageUrls: string[];
    preferredSupplier: string | null;
    supplierId: string | null;
    isActive: boolean;
    isFeatured: boolean;
    attributes: import("@prisma/client/runtime/library").JsonValue;
}[]>;
export declare function listProducts(): Promise<{
    tenantId: string;
    id: string;
    name: string;
    tags: string[];
    createdBy: string | null;
    updatedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    cess: Decimal;
    description: string | null;
    category: string;
    unit: string;
    mrp: Decimal | null;
    hsnCode: string | null;
    gstRate: Decimal;
    subCategory: string | null;
    sku: string | null;
    barcode: string | null;
    price: Decimal;
    cost: Decimal | null;
    wholesalePrice: Decimal | null;
    priceTier2: Decimal | null;
    priceTier3: Decimal | null;
    baseUnit: string | null;
    baseUnitQuantity: Decimal | null;
    stock: number;
    minStock: number;
    maxStock: number | null;
    location: string | null;
    isGstExempt: boolean;
    trackBatches: boolean;
    trackSerialNumbers: boolean;
    hasVariants: boolean;
    imageUrl: string | null;
    imageUrls: string[];
    preferredSupplier: string | null;
    supplierId: string | null;
    isActive: boolean;
    isFeatured: boolean;
    attributes: import("@prisma/client/runtime/library").JsonValue;
}[]>;
export declare function listProductsPaginated(page?: number, limit?: number): Promise<{
    products: {
        tenantId: string;
        id: string;
        name: string;
        tags: string[];
        createdBy: string | null;
        updatedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        cess: Decimal;
        description: string | null;
        category: string;
        unit: string;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        subCategory: string | null;
        sku: string | null;
        barcode: string | null;
        price: Decimal;
        cost: Decimal | null;
        wholesalePrice: Decimal | null;
        priceTier2: Decimal | null;
        priceTier3: Decimal | null;
        baseUnit: string | null;
        baseUnitQuantity: Decimal | null;
        stock: number;
        minStock: number;
        maxStock: number | null;
        location: string | null;
        isGstExempt: boolean;
        trackBatches: boolean;
        trackSerialNumbers: boolean;
        hasVariants: boolean;
        imageUrl: string | null;
        imageUrls: string[];
        preferredSupplier: string | null;
        supplierId: string | null;
        isActive: boolean;
        isFeatured: boolean;
        attributes: import("@prisma/client/runtime/library").JsonValue;
    }[];
    total: number;
    page: number;
    limit: number;
    hasMore: boolean;
}>;
export declare function getLowStockProducts(): Promise<{
    id: string;
    name: string;
    category: string;
    description: string | null;
    price: string;
    unit: string;
    stock: number;
    minStock: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
}[]>;
export declare function getExpiringBatches(days?: number): Promise<({
    product: {
        name: string;
        unit: string;
    };
} & {
    tenantId: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: string;
    productId: string;
    quantity: number;
    batchNo: string;
    expiryDate: Date;
    variantId: string | null;
    location: string | null;
    supplierId: string | null;
    manufacturingDate: Date | null;
    initialQuantity: number;
    purchasePrice: Decimal | null;
    purchaseDate: Date | null;
})[]>;
export declare function getExpiryPage(filter?: "expired" | "7d" | "30d" | "90d" | "all"): Promise<{
    batches: ({
        product: {
            name: string;
            category: string;
            unit: string;
        };
    } & {
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        productId: string;
        quantity: number;
        batchNo: string;
        expiryDate: Date;
        variantId: string | null;
        location: string | null;
        supplierId: string | null;
        manufacturingDate: Date | null;
        initialQuantity: number;
        purchasePrice: Decimal | null;
        purchaseDate: Date | null;
    })[];
    summary: {
        expiredCount: number;
        expiringIn7: number;
        expiringIn30: number;
        totalExpiredValue: number;
        filter: "expired" | "7d" | "30d" | "90d" | "all";
    };
}>;
export declare function createProduct(data: {
    name: string;
    price: number;
    stock: number;
    description?: string;
    unit?: string;
    category?: string;
    barcode?: string;
    sku?: string;
    wholesalePrice?: number;
    priceTier2?: number;
    priceTier3?: number;
}): Promise<{
    tenantId: string;
    id: string;
    name: string;
    tags: string[];
    createdBy: string | null;
    updatedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    cess: Decimal;
    description: string | null;
    category: string;
    unit: string;
    mrp: Decimal | null;
    hsnCode: string | null;
    gstRate: Decimal;
    subCategory: string | null;
    sku: string | null;
    barcode: string | null;
    price: Decimal;
    cost: Decimal | null;
    wholesalePrice: Decimal | null;
    priceTier2: Decimal | null;
    priceTier3: Decimal | null;
    baseUnit: string | null;
    baseUnitQuantity: Decimal | null;
    stock: number;
    minStock: number;
    maxStock: number | null;
    location: string | null;
    isGstExempt: boolean;
    trackBatches: boolean;
    trackSerialNumbers: boolean;
    hasVariants: boolean;
    imageUrl: string | null;
    imageUrls: string[];
    preferredSupplier: string | null;
    supplierId: string | null;
    isActive: boolean;
    isFeatured: boolean;
    attributes: import("@prisma/client/runtime/library").JsonValue;
}>;
export declare function updateProduct(productId: string, data: {
    name?: string;
    price?: number;
    stock?: number;
    unit?: string;
    category?: string;
    description?: string;
    barcode?: string;
    sku?: string;
    minStock?: number;
    wholesalePrice?: number;
    priceTier2?: number;
    priceTier3?: number;
    isFeatured?: boolean;
    gstRate?: number;
    hsnCode?: string;
    cost?: number;
    mrp?: number;
}): Promise<{
    tenantId: string;
    id: string;
    name: string;
    tags: string[];
    createdBy: string | null;
    updatedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    cess: Decimal;
    description: string | null;
    category: string;
    unit: string;
    mrp: Decimal | null;
    hsnCode: string | null;
    gstRate: Decimal;
    subCategory: string | null;
    sku: string | null;
    barcode: string | null;
    price: Decimal;
    cost: Decimal | null;
    wholesalePrice: Decimal | null;
    priceTier2: Decimal | null;
    priceTier3: Decimal | null;
    baseUnit: string | null;
    baseUnitQuantity: Decimal | null;
    stock: number;
    minStock: number;
    maxStock: number | null;
    location: string | null;
    isGstExempt: boolean;
    trackBatches: boolean;
    trackSerialNumbers: boolean;
    hasVariants: boolean;
    imageUrl: string | null;
    imageUrls: string[];
    preferredSupplier: string | null;
    supplierId: string | null;
    isActive: boolean;
    isFeatured: boolean;
    attributes: import("@prisma/client/runtime/library").JsonValue;
}>;
export declare function updateProductStock(productId: string, quantity: number, operation: "add" | "subtract"): Promise<{
    tenantId: string;
    id: string;
    name: string;
    tags: string[];
    createdBy: string | null;
    updatedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    cess: Decimal;
    description: string | null;
    category: string;
    unit: string;
    mrp: Decimal | null;
    hsnCode: string | null;
    gstRate: Decimal;
    subCategory: string | null;
    sku: string | null;
    barcode: string | null;
    price: Decimal;
    cost: Decimal | null;
    wholesalePrice: Decimal | null;
    priceTier2: Decimal | null;
    priceTier3: Decimal | null;
    baseUnit: string | null;
    baseUnitQuantity: Decimal | null;
    stock: number;
    minStock: number;
    maxStock: number | null;
    location: string | null;
    isGstExempt: boolean;
    trackBatches: boolean;
    trackSerialNumbers: boolean;
    hasVariants: boolean;
    imageUrl: string | null;
    imageUrls: string[];
    preferredSupplier: string | null;
    supplierId: string | null;
    isActive: boolean;
    isFeatured: boolean;
    attributes: import("@prisma/client/runtime/library").JsonValue;
}>;
export declare function writeOffBatch(batchId: string): Promise<{
    ok: boolean;
    batchId: string;
}>;
//# sourceMappingURL=product.d.ts.map