import { InvoiceItemInput } from '@execora/types';
import { Decimal } from '@prisma/client/runtime/library';
import { type SupplyType } from '../gst/gst.service';
declare class InvoiceService {
    /**
     * Find a product by name using a two-pass strategy:
     * 1) Exact case-insensitive contains match (fast).
     * 2) Fuzzy fallback — normalise both strings, pick best overlap.
     * This handles spoken/transliterated names ("cheeni" → "Cheeni", "aata" → "Atta").
     */
    /**
     * Find a product by name (two-pass: exact contains, then fuzzy).
     * If still not found, auto-creates the product with price=0 so invoices never block.
     * Returns { product, autoCreated } so callers can warn the shopkeeper.
     */
    private findOrCreateProduct;
    /**
     * Preview invoice — resolves products (auto-creates unknowns at ₹0), optionally
     * calculates GST per line item, and returns fully priced items WITHOUT committing to the DB.
     * The caller should store the result in Redis and wait for user confirmation.
     *
     * @param withGst  — Default FALSE. Pass true only when user explicitly requests GST billing.
     * @param supplyType — Only relevant when withGst=true. Determines CGST+SGST vs IGST split.
     */
    previewInvoice(customerId: string, items: InvoiceItemInput[], withGst?: boolean, supplyType?: SupplyType): Promise<{
        resolvedItems: Array<{
            productId: string;
            productName: string;
            unit: string;
            hsnCode: string | null;
            quantity: number;
            unitPrice: number;
            gstRate: number;
            cessRate: number;
            isGstExempt: boolean;
            cgst: number;
            sgst: number;
            igst: number;
            cess: number;
            subtotal: number;
            totalTax: number;
            total: number;
            autoCreated: boolean;
        }>;
        subtotal: number;
        totalCgst: number;
        totalSgst: number;
        totalIgst: number;
        totalCess: number;
        totalTax: number;
        grandTotal: number;
        autoCreatedProducts: string[];
    }>;
    /**
     * Confirm invoice — creates the DB record from already-resolved items (with GST).
     * Call this after the user confirms the preview returned by previewInvoice().
     */
    confirmInvoice(customerId: string, resolvedItems: Array<{
        productId: string;
        productName: string;
        unit: string;
        hsnCode?: string | null;
        quantity: number;
        unitPrice: number;
        gstRate?: number;
        cessRate?: number;
        isGstExempt?: boolean;
        cgst?: number;
        sgst?: number;
        igst?: number;
        cess?: number;
        subtotal?: number;
        totalTax?: number;
        total: number;
    }>, notes?: string): Promise<{
        customer: {
            balance: Decimal;
            creditLimit: Decimal;
            totalPurchases: Decimal;
            totalPayments: Decimal;
            lastPaymentAmount: Decimal | null;
            averagePaymentDays: number | null;
            loyaltyPoints: number;
            visitCount: number;
            averageBasketSize: Decimal | null;
            frequencyScore: Decimal;
            recencyScore: Decimal;
            monetaryScore: Decimal;
            overallScore: Decimal | null;
            id: string;
            tenantId: string;
            name: string;
            phone: string | null;
            alternatePhone: string[];
            email: string | null;
            honorific: string | null;
            localName: string | null;
            nickname: string[];
            addressLine1: string | null;
            addressLine2: string | null;
            landmark: string | null;
            area: string | null;
            city: string | null;
            district: string | null;
            state: string | null;
            pincode: string | null;
            gstin: string | null;
            pan: string | null;
            businessType: string | null;
            lastPaymentDate: Date | null;
            loyaltyTier: string;
            firstVisit: Date | null;
            lastVisit: Date | null;
            preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
            preferredTimeOfDay: Date | null;
            preferredDays: string[];
            tags: string[];
            notes: string | null;
            metadata: import("@prisma/client/runtime/library").JsonValue;
            voiceFingerprint: string | null;
            commonPhrases: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
        } | null;
        items: ({
            product: {
                id: string;
                tenantId: string;
                name: string;
                tags: string[];
                createdBy: string | null;
                updatedBy: string | null;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                cess: Decimal;
                description: string | null;
                unit: string;
                mrp: Decimal | null;
                hsnCode: string | null;
                gstRate: Decimal;
                category: string;
                subCategory: string | null;
                sku: string | null;
                barcode: string | null;
                price: Decimal;
                cost: Decimal | null;
                baseUnit: string | null;
                baseUnitQuantity: Decimal | null;
                stock: number;
                minStock: number;
                maxStock: number | null;
                location: string | null;
                isGstExempt: boolean;
                trackBatches: boolean;
                trackSerialNumbers: boolean;
                hasVariants: boolean;
                imageUrl: string | null;
                imageUrls: string[];
                preferredSupplier: string | null;
                supplierId: string | null;
                isActive: boolean;
                isFeatured: boolean;
                attributes: import("@prisma/client/runtime/library").JsonValue;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            serialNumbers: string[];
            subtotal: Decimal;
            discount: Decimal;
            total: Decimal;
            tax: Decimal;
            cgst: Decimal;
            sgst: Decimal;
            igst: Decimal;
            cess: Decimal;
            invoiceId: string;
            productId: string | null;
            productName: string;
            variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
            quantity: Decimal;
            unit: string;
            unitPrice: Decimal;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            variantId: string | null;
            batchId: string | null;
        })[];
    } & {
        id: string;
        tenantId: string;
        notes: string | null;
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNo: string;
        customerId: string | null;
        subtotal: Decimal;
        discount: Decimal;
        discountType: string | null;
        total: Decimal;
        paidAmount: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        placeOfSupply: string | null;
        reverseCharge: boolean;
        ewayBillNo: string | null;
        ewayBillGeneratedAt: Date | null;
        irn: string | null;
        irnGeneratedAt: Date | null;
        ackNo: string | null;
        ackDate: Date | null;
        qrCode: string | null;
        paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
        invoiceDate: Date;
        dueDate: Date | null;
        paidAt: Date | null;
        pdfObjectKey: string | null;
        pdfUrl: string | null;
    }>;
    /**
     * Create invoice with atomic transaction.
     * Finds products by name, checks stock, creates invoice + items, updates stock + customer balance.
     */
    createInvoice(customerId: string, items: InvoiceItemInput[], notes?: string): Promise<{
        invoice: {
            customer: {
                balance: Decimal;
                creditLimit: Decimal;
                totalPurchases: Decimal;
                totalPayments: Decimal;
                lastPaymentAmount: Decimal | null;
                averagePaymentDays: number | null;
                loyaltyPoints: number;
                visitCount: number;
                averageBasketSize: Decimal | null;
                frequencyScore: Decimal;
                recencyScore: Decimal;
                monetaryScore: Decimal;
                overallScore: Decimal | null;
                id: string;
                tenantId: string;
                name: string;
                phone: string | null;
                alternatePhone: string[];
                email: string | null;
                honorific: string | null;
                localName: string | null;
                nickname: string[];
                addressLine1: string | null;
                addressLine2: string | null;
                landmark: string | null;
                area: string | null;
                city: string | null;
                district: string | null;
                state: string | null;
                pincode: string | null;
                gstin: string | null;
                pan: string | null;
                businessType: string | null;
                lastPaymentDate: Date | null;
                loyaltyTier: string;
                firstVisit: Date | null;
                lastVisit: Date | null;
                preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
                preferredTimeOfDay: Date | null;
                preferredDays: string[];
                tags: string[];
                notes: string | null;
                metadata: import("@prisma/client/runtime/library").JsonValue;
                voiceFingerprint: string | null;
                commonPhrases: string[];
                createdBy: string | null;
                updatedBy: string | null;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
            } | null;
            items: ({
                product: {
                    id: string;
                    tenantId: string;
                    name: string;
                    tags: string[];
                    createdBy: string | null;
                    updatedBy: string | null;
                    createdAt: Date;
                    updatedAt: Date;
                    deletedAt: Date | null;
                    cess: Decimal;
                    description: string | null;
                    unit: string;
                    mrp: Decimal | null;
                    hsnCode: string | null;
                    gstRate: Decimal;
                    category: string;
                    subCategory: string | null;
                    sku: string | null;
                    barcode: string | null;
                    price: Decimal;
                    cost: Decimal | null;
                    baseUnit: string | null;
                    baseUnitQuantity: Decimal | null;
                    stock: number;
                    minStock: number;
                    maxStock: number | null;
                    location: string | null;
                    isGstExempt: boolean;
                    trackBatches: boolean;
                    trackSerialNumbers: boolean;
                    hasVariants: boolean;
                    imageUrl: string | null;
                    imageUrls: string[];
                    preferredSupplier: string | null;
                    supplierId: string | null;
                    isActive: boolean;
                    isFeatured: boolean;
                    attributes: import("@prisma/client/runtime/library").JsonValue;
                } | null;
            } & {
                id: string;
                createdAt: Date;
                serialNumbers: string[];
                subtotal: Decimal;
                discount: Decimal;
                total: Decimal;
                tax: Decimal;
                cgst: Decimal;
                sgst: Decimal;
                igst: Decimal;
                cess: Decimal;
                invoiceId: string;
                productId: string | null;
                productName: string;
                variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
                quantity: Decimal;
                unit: string;
                unitPrice: Decimal;
                mrp: Decimal | null;
                hsnCode: string | null;
                gstRate: Decimal;
                variantId: string | null;
                batchId: string | null;
            })[];
        } & {
            id: string;
            tenantId: string;
            notes: string | null;
            createdBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            invoiceNo: string;
            customerId: string | null;
            subtotal: Decimal;
            discount: Decimal;
            discountType: string | null;
            total: Decimal;
            paidAmount: Decimal;
            tax: Decimal;
            cgst: Decimal;
            sgst: Decimal;
            igst: Decimal;
            cess: Decimal;
            placeOfSupply: string | null;
            reverseCharge: boolean;
            ewayBillNo: string | null;
            ewayBillGeneratedAt: Date | null;
            irn: string | null;
            irnGeneratedAt: Date | null;
            ackNo: string | null;
            ackDate: Date | null;
            qrCode: string | null;
            paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
            invoiceDate: Date;
            dueDate: Date | null;
            paidAt: Date | null;
            pdfObjectKey: string | null;
            pdfUrl: string | null;
        };
        autoCreatedProducts: string[];
    }>;
    /**
     * Cancel invoice — reverses stock and customer balance.
     */
    cancelInvoice(invoiceId: string): Promise<{
        items: ({
            product: {
                id: string;
                tenantId: string;
                name: string;
                tags: string[];
                createdBy: string | null;
                updatedBy: string | null;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                cess: Decimal;
                description: string | null;
                unit: string;
                mrp: Decimal | null;
                hsnCode: string | null;
                gstRate: Decimal;
                category: string;
                subCategory: string | null;
                sku: string | null;
                barcode: string | null;
                price: Decimal;
                cost: Decimal | null;
                baseUnit: string | null;
                baseUnitQuantity: Decimal | null;
                stock: number;
                minStock: number;
                maxStock: number | null;
                location: string | null;
                isGstExempt: boolean;
                trackBatches: boolean;
                trackSerialNumbers: boolean;
                hasVariants: boolean;
                imageUrl: string | null;
                imageUrls: string[];
                preferredSupplier: string | null;
                supplierId: string | null;
                isActive: boolean;
                isFeatured: boolean;
                attributes: import("@prisma/client/runtime/library").JsonValue;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            serialNumbers: string[];
            subtotal: Decimal;
            discount: Decimal;
            total: Decimal;
            tax: Decimal;
            cgst: Decimal;
            sgst: Decimal;
            igst: Decimal;
            cess: Decimal;
            invoiceId: string;
            productId: string | null;
            productName: string;
            variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
            quantity: Decimal;
            unit: string;
            unitPrice: Decimal;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            variantId: string | null;
            batchId: string | null;
        })[];
    } & {
        id: string;
        tenantId: string;
        notes: string | null;
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNo: string;
        customerId: string | null;
        subtotal: Decimal;
        discount: Decimal;
        discountType: string | null;
        total: Decimal;
        paidAmount: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        placeOfSupply: string | null;
        reverseCharge: boolean;
        ewayBillNo: string | null;
        ewayBillGeneratedAt: Date | null;
        irn: string | null;
        irnGeneratedAt: Date | null;
        ackNo: string | null;
        ackDate: Date | null;
        qrCode: string | null;
        paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
        invoiceDate: Date;
        dueDate: Date | null;
        paidAt: Date | null;
        pdfObjectKey: string | null;
        pdfUrl: string | null;
    }>;
    /**
     * Get recent invoices.
     */
    getRecentInvoices(limit?: number): Promise<({
        customer: {
            balance: Decimal;
            creditLimit: Decimal;
            totalPurchases: Decimal;
            totalPayments: Decimal;
            lastPaymentAmount: Decimal | null;
            averagePaymentDays: number | null;
            loyaltyPoints: number;
            visitCount: number;
            averageBasketSize: Decimal | null;
            frequencyScore: Decimal;
            recencyScore: Decimal;
            monetaryScore: Decimal;
            overallScore: Decimal | null;
            id: string;
            tenantId: string;
            name: string;
            phone: string | null;
            alternatePhone: string[];
            email: string | null;
            honorific: string | null;
            localName: string | null;
            nickname: string[];
            addressLine1: string | null;
            addressLine2: string | null;
            landmark: string | null;
            area: string | null;
            city: string | null;
            district: string | null;
            state: string | null;
            pincode: string | null;
            gstin: string | null;
            pan: string | null;
            businessType: string | null;
            lastPaymentDate: Date | null;
            loyaltyTier: string;
            firstVisit: Date | null;
            lastVisit: Date | null;
            preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
            preferredTimeOfDay: Date | null;
            preferredDays: string[];
            tags: string[];
            notes: string | null;
            metadata: import("@prisma/client/runtime/library").JsonValue;
            voiceFingerprint: string | null;
            commonPhrases: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
        } | null;
        items: ({
            product: {
                id: string;
                tenantId: string;
                name: string;
                tags: string[];
                createdBy: string | null;
                updatedBy: string | null;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                cess: Decimal;
                description: string | null;
                unit: string;
                mrp: Decimal | null;
                hsnCode: string | null;
                gstRate: Decimal;
                category: string;
                subCategory: string | null;
                sku: string | null;
                barcode: string | null;
                price: Decimal;
                cost: Decimal | null;
                baseUnit: string | null;
                baseUnitQuantity: Decimal | null;
                stock: number;
                minStock: number;
                maxStock: number | null;
                location: string | null;
                isGstExempt: boolean;
                trackBatches: boolean;
                trackSerialNumbers: boolean;
                hasVariants: boolean;
                imageUrl: string | null;
                imageUrls: string[];
                preferredSupplier: string | null;
                supplierId: string | null;
                isActive: boolean;
                isFeatured: boolean;
                attributes: import("@prisma/client/runtime/library").JsonValue;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            serialNumbers: string[];
            subtotal: Decimal;
            discount: Decimal;
            total: Decimal;
            tax: Decimal;
            cgst: Decimal;
            sgst: Decimal;
            igst: Decimal;
            cess: Decimal;
            invoiceId: string;
            productId: string | null;
            productName: string;
            variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
            quantity: Decimal;
            unit: string;
            unitPrice: Decimal;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            variantId: string | null;
            batchId: string | null;
        })[];
    } & {
        id: string;
        tenantId: string;
        notes: string | null;
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNo: string;
        customerId: string | null;
        subtotal: Decimal;
        discount: Decimal;
        discountType: string | null;
        total: Decimal;
        paidAmount: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        placeOfSupply: string | null;
        reverseCharge: boolean;
        ewayBillNo: string | null;
        ewayBillGeneratedAt: Date | null;
        irn: string | null;
        irnGeneratedAt: Date | null;
        ackNo: string | null;
        ackDate: Date | null;
        qrCode: string | null;
        paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
        invoiceDate: Date;
        dueDate: Date | null;
        paidAt: Date | null;
        pdfObjectKey: string | null;
        pdfUrl: string | null;
    })[]>;
    /**
     * Get all invoices for a customer.
     */
    getCustomerInvoices(customerId: string, limit?: number): Promise<({
        items: ({
            product: {
                id: string;
                tenantId: string;
                name: string;
                tags: string[];
                createdBy: string | null;
                updatedBy: string | null;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                cess: Decimal;
                description: string | null;
                unit: string;
                mrp: Decimal | null;
                hsnCode: string | null;
                gstRate: Decimal;
                category: string;
                subCategory: string | null;
                sku: string | null;
                barcode: string | null;
                price: Decimal;
                cost: Decimal | null;
                baseUnit: string | null;
                baseUnitQuantity: Decimal | null;
                stock: number;
                minStock: number;
                maxStock: number | null;
                location: string | null;
                isGstExempt: boolean;
                trackBatches: boolean;
                trackSerialNumbers: boolean;
                hasVariants: boolean;
                imageUrl: string | null;
                imageUrls: string[];
                preferredSupplier: string | null;
                supplierId: string | null;
                isActive: boolean;
                isFeatured: boolean;
                attributes: import("@prisma/client/runtime/library").JsonValue;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            serialNumbers: string[];
            subtotal: Decimal;
            discount: Decimal;
            total: Decimal;
            tax: Decimal;
            cgst: Decimal;
            sgst: Decimal;
            igst: Decimal;
            cess: Decimal;
            invoiceId: string;
            productId: string | null;
            productName: string;
            variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
            quantity: Decimal;
            unit: string;
            unitPrice: Decimal;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            variantId: string | null;
            batchId: string | null;
        })[];
    } & {
        id: string;
        tenantId: string;
        notes: string | null;
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNo: string;
        customerId: string | null;
        subtotal: Decimal;
        discount: Decimal;
        discountType: string | null;
        total: Decimal;
        paidAmount: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        placeOfSupply: string | null;
        reverseCharge: boolean;
        ewayBillNo: string | null;
        ewayBillGeneratedAt: Date | null;
        irn: string | null;
        irnGeneratedAt: Date | null;
        ackNo: string | null;
        ackDate: Date | null;
        qrCode: string | null;
        paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
        invoiceDate: Date;
        dueDate: Date | null;
        paidAt: Date | null;
        pdfObjectKey: string | null;
        pdfUrl: string | null;
    })[]>;
    /**
     * Get the most recent non-cancelled invoice for a customer.
     */
    getLastInvoice(customerId: string): Promise<({
        items: ({
            product: {
                id: string;
                tenantId: string;
                name: string;
                tags: string[];
                createdBy: string | null;
                updatedBy: string | null;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                cess: Decimal;
                description: string | null;
                unit: string;
                mrp: Decimal | null;
                hsnCode: string | null;
                gstRate: Decimal;
                category: string;
                subCategory: string | null;
                sku: string | null;
                barcode: string | null;
                price: Decimal;
                cost: Decimal | null;
                baseUnit: string | null;
                baseUnitQuantity: Decimal | null;
                stock: number;
                minStock: number;
                maxStock: number | null;
                location: string | null;
                isGstExempt: boolean;
                trackBatches: boolean;
                trackSerialNumbers: boolean;
                hasVariants: boolean;
                imageUrl: string | null;
                imageUrls: string[];
                preferredSupplier: string | null;
                supplierId: string | null;
                isActive: boolean;
                isFeatured: boolean;
                attributes: import("@prisma/client/runtime/library").JsonValue;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            serialNumbers: string[];
            subtotal: Decimal;
            discount: Decimal;
            total: Decimal;
            tax: Decimal;
            cgst: Decimal;
            sgst: Decimal;
            igst: Decimal;
            cess: Decimal;
            invoiceId: string;
            productId: string | null;
            productName: string;
            variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
            quantity: Decimal;
            unit: string;
            unitPrice: Decimal;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            variantId: string | null;
            batchId: string | null;
        })[];
    } & {
        id: string;
        tenantId: string;
        notes: string | null;
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNo: string;
        customerId: string | null;
        subtotal: Decimal;
        discount: Decimal;
        discountType: string | null;
        total: Decimal;
        paidAmount: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        placeOfSupply: string | null;
        reverseCharge: boolean;
        ewayBillNo: string | null;
        ewayBillGeneratedAt: Date | null;
        irn: string | null;
        irnGeneratedAt: Date | null;
        ackNo: string | null;
        ackDate: Date | null;
        qrCode: string | null;
        paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
        invoiceDate: Date;
        dueDate: Date | null;
        paidAt: Date | null;
        pdfObjectKey: string | null;
        pdfUrl: string | null;
    }) | null>;
    /**
     * Persist the MinIO object key (and presigned URL) on an invoice record.
     * Called after the PDF is uploaded so the URL can be regenerated any time.
     */
    savePdfUrl(invoiceId: string, pdfObjectKey: string, pdfUrl: string): Promise<void>;
    /**
     * Daily sales summary.
     */
    getDailySummary(date?: Date): Promise<{
        date: Date;
        invoiceCount: number;
        totalSales: number;
        totalPayments: number;
        cashPayments: number;
        upiPayments: number;
        pendingAmount: number;
        extraPayments: number;
    }>;
}
export declare const invoiceService: InvoiceService;
export {};
//# sourceMappingURL=invoice.service.d.ts.map