#!/usr/bin/env bash
# =============================================================================
# Execora — One-command installer
# Usage:  bash install.sh
# =============================================================================
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${CYAN}▸${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✗${NC} $*"; exit 1; }
header()  { echo -e "\n${BOLD}${BLUE}$*${NC}"; echo "──────────────────────────────────────────"; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
cat << 'EOF'
  ███████╗██╗  ██╗███████╗ ██████╗ ██████╗ ██████╗  █████╗
  ██╔════╝╚██╗██╔╝██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔══██╗
  █████╗   ╚███╔╝ █████╗  ██║     ██║   ██║██████╔╝███████║
  ██╔══╝   ██╔██╗ ██╔══╝  ██║     ██║   ██║██╔══██╗██╔══██║
  ███████╗██╔╝ ██╗███████╗╚██████╗╚██████╔╝██║  ██║██║  ██║
  ╚══════╝╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
EOF
echo -e "${NC}${CYAN}  Indian Kirana & Retail Billing — GST Compliant${NC}"
echo -e "  Version 1.0 · Setup Wizard\n"

# ── 1. Prerequisites check ────────────────────────────────────────────────────
header "Step 1/5 — Checking prerequisites"

command -v docker >/dev/null 2>&1 || error "Docker not found. Install from https://docs.docker.com/get-docker/"
success "Docker found: $(docker --version | cut -d' ' -f3 | tr -d ',')"

# Support both docker-compose (v1) and docker compose (v2)
if command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
elif docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
else
  error "Docker Compose not found. Install from https://docs.docker.com/compose/install/"
fi
success "Docker Compose found"

command -v openssl >/dev/null 2>&1 || error "openssl not found. Install it (e.g. apt install openssl)"
success "openssl found"

# ── 2. Shop setup questions ───────────────────────────────────────────────────
header "Step 2/5 — Shop setup"

echo "We'll set up your Execora billing system now."
echo "Press Enter to accept [defaults shown in brackets]."
echo ""

read -rp "  Shop / Business name  [My Kirana Store]: " SHOP_NAME
SHOP_NAME="${SHOP_NAME:-My Kirana Store}"

read -rp "  City / Location       [Delhi]: " SHOP_CITY
SHOP_CITY="${SHOP_CITY:-Delhi}"

read -rp "  Business type (kirana/retail/wholesale) [kirana]: " BUSINESS_TYPE
BUSINESS_TYPE="${BUSINESS_TYPE:-kirana}"

read -rp "  Admin email           [admin@example.com]: " ADMIN_EMAIL
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"

while true; do
  read -rsp "  Admin password        (min 8 chars): " ADMIN_PASSWORD
  echo ""
  if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
    break
  fi
  warn "Password must be at least 8 characters."
done

read -rp "  App port              [80]: " APP_PORT
APP_PORT="${APP_PORT:-80}"

echo ""
success "Shop: ${SHOP_NAME} (${BUSINESS_TYPE}) · ${SHOP_CITY}"
success "Admin: ${ADMIN_EMAIL}"
success "Port: ${APP_PORT}"

# ── 3. Generate .env ──────────────────────────────────────────────────────────
header "Step 3/5 — Generating configuration"

# Auto-generate secrets
JWT_SECRET=$(openssl rand -hex 32)
ADMIN_API_KEY=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 16)
REDIS_PASSWORD=$(openssl rand -hex 16)
MINIO_SECRET=$(openssl rand -hex 16)

# Hash admin password with bcrypt (node built-in via docker or local node)
if command -v node >/dev/null 2>&1; then
  ADMIN_PASSWORD_HASH=$(node -e "
    const crypto = require('crypto');
    const bcrypt = require('bcryptjs') || null;
    // Try bcryptjs
    try {
      const b = require('bcryptjs');
      b.hash('${ADMIN_PASSWORD}', 10).then(h => { process.stdout.write(h); process.exit(0); });
    } catch(e) {
      // Fallback: we'll set it later via docker
      process.stdout.write('PENDING');
      process.exit(0);
    }
  " 2>/dev/null || echo "PENDING")
else
  ADMIN_PASSWORD_HASH="PENDING"
fi

cat > .env << EOF
# =============================================================================
# Execora — Generated by install.sh on $(date)
# =============================================================================

NODE_ENV=production
PORT=3006
HOST=0.0.0.0
TZ=Asia/Kolkata

ALLOWED_ORIGINS=http://localhost:${APP_PORT}

# Database
DATABASE_URL=postgresql://execora:${POSTGRES_PASSWORD}@postgres:5432/execora?schema=public
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}

# MinIO
MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_ACCESS_KEY=execora
MINIO_SECRET_KEY=${MINIO_SECRET}
MINIO_BUCKET=execora
MINIO_ROOT_USER=execora
MINIO_ROOT_PASSWORD=${MINIO_SECRET}
MINIO_USE_SSL=false

# Auth
JWT_SECRET=${JWT_SECRET}
JWT_ACCESS_EXPIRES_SECONDS=900
JWT_REFRESH_EXPIRES_SECONDS=604800
ADMIN_API_KEY=${ADMIN_API_KEY}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_NAME=Admin
ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}

# Business
SYSTEM_TENANT_ID=system-tenant-001
SYSTEM_USER_ID=system-user-001
BUSINESS_NAME=${SHOP_NAME}
BUSINESS_TYPE=${BUSINESS_TYPE}
SHOP_CITY=${SHOP_CITY}
SHOP_NAME=${SHOP_NAME}

# LLM (optional — voice features require these)
OPENAI_API_KEY=
GROQ_API_KEY=

# STT/TTS (optional — voice features)
STT_PROVIDER=deepgram
DEEPGRAM_API_KEY=
TTS_PROVIDER=elevenlabs
ELEVENLABS_API_KEY=

# Logging
LOG_LEVEL=info
EOF

success ".env generated with auto-generated secrets"

# Set correct port in nginx env
echo "APP_PORT=${APP_PORT}" >> .env

# ── 4. Start Docker stack ─────────────────────────────────────────────────────
header "Step 4/5 — Starting Execora"

info "Building and starting containers (this may take 3–5 minutes on first run)..."

$COMPOSE -f docker-compose.dist.yml up -d --build

info "Waiting for database to be ready..."
for i in $(seq 1 30); do
  if $COMPOSE -f docker-compose.dist.yml exec -T postgres pg_isready -U execora >/dev/null 2>&1; then
    success "Database ready"
    break
  fi
  if [ "$i" -eq 30 ]; then
    error "Database did not start in time. Check: $COMPOSE -f docker-compose.dist.yml logs postgres"
  fi
  sleep 2
done

info "Waiting for API to be ready..."
for i in $(seq 1 40); do
  if $COMPOSE -f docker-compose.dist.yml exec -T app node -e "require('http').get('http://localhost:3006/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))" >/dev/null 2>&1; then
    success "API ready"
    break
  fi
  if [ "$i" -eq 40 ]; then
    error "API did not start in time. Check: $COMPOSE -f docker-compose.dist.yml logs app"
  fi
  sleep 3
done

# ── 5. Seed demo data ─────────────────────────────────────────────────────────
header "Step 5/5 — Loading demo data"

info "Seeding products, demo customers, and sample invoices..."
$COMPOSE -f docker-compose.dist.yml exec -T app node -e "
  const { execSync } = require('child_process');
  execSync('pnpm exec prisma db seed', { stdio: 'inherit', cwd: '/app' });
" 2>/dev/null || $COMPOSE -f docker-compose.dist.yml exec -T app sh -c "cd /app && pnpm exec prisma db seed" || warn "Seed skipped (non-critical)"

# Compute admin password hash inside container (bcryptjs is available there)
if [ "$ADMIN_PASSWORD_HASH" = "PENDING" ]; then
  info "Computing admin password hash..."
  HASH=$($COMPOSE -f docker-compose.dist.yml exec -T app node -e \
    "const b=require('bcryptjs');b.hash('${ADMIN_PASSWORD}',10).then(h=>{process.stdout.write(h);process.exit(0);})" 2>/dev/null || echo "")
  if [ -n "$HASH" ]; then
    sed -i "s|ADMIN_PASSWORD_HASH=PENDING|ADMIN_PASSWORD_HASH=${HASH}|" .env
    # Restart app to pick up updated hash
    $COMPOSE -f docker-compose.dist.yml restart app >/dev/null 2>&1 || true
    success "Admin password set"
  fi
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║          Execora is ready!                          ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}App URL:${NC}       http://localhost:${APP_PORT}"
echo -e "  ${BOLD}Admin email:${NC}   ${ADMIN_EMAIL}"
echo -e "  ${BOLD}Shop name:${NC}     ${SHOP_NAME}"
echo ""
echo -e "  ${CYAN}Management commands:${NC}"
echo -e "    Stop:     $COMPOSE -f docker-compose.dist.yml down"
echo -e "    Restart:  $COMPOSE -f docker-compose.dist.yml restart"
echo -e "    Logs:     $COMPOSE -f docker-compose.dist.yml logs -f"
echo -e "    Update:   git pull && $COMPOSE -f docker-compose.dist.yml up -d --build"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "    1. Open http://localhost:${APP_PORT} and log in"
echo -e "    2. Go to Settings → add your GSTIN, UPI ID, shop address"
echo -e "    3. Add API keys in Settings → Integrations (voice/WhatsApp, optional)"
echo ""

# Try to open browser (Linux/Mac)
if command -v xdg-open >/dev/null 2>&1; then
  xdg-open "http://localhost:${APP_PORT}" >/dev/null 2>&1 || true
elif command -v open >/dev/null 2>&1; then
  open "http://localhost:${APP_PORT}" >/dev/null 2>&1 || true
fi
