/**
 * CRM domain — customer business operations.
 *
 * Direct Prisma calls, flat async functions, no class wrappers.
 * Voice-engine-specific methods (context cache, ranked search, balance streaming)
 * remain in modules/customer/customer.service.ts (legacy, voice layer only).
 */
import { Decimal } from "@prisma/client/runtime/library";
import type { CustomerSearchResult } from "@execora/types";
export declare function getCustomerById(id: string): Promise<({
    reminders: {
        tenantId: string;
        id: string;
        customerId: string | null;
        status: import(".prisma/client").$Enums.ReminderStatus;
        notes: string | null;
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        invoiceId: string | null;
        productId: string | null;
        userId: string | null;
        scheduledTime: Date;
        reminderType: import(".prisma/client").$Enums.ReminderType;
        priority: import(".prisma/client").$Enums.ReminderPriority;
        recurringPattern: import("@prisma/client/runtime/library").JsonValue | null;
        expiresAt: Date | null;
        messageTemplateId: string | null;
        customMessage: string | null;
        parameters: import("@prisma/client/runtime/library").JsonValue | null;
        channels: import(".prisma/client").$Enums.MessageChannel[];
        sentAt: Date | null;
        deliveredAt: Date | null;
        readAt: Date | null;
        retryCount: number;
        maxRetries: number;
        lastAttempt: Date | null;
        lastError: string | null;
    }[];
    invoices: {
        tenantId: string;
        id: string;
        invoiceNo: string;
        customerId: string | null;
        subtotal: Decimal;
        discount: Decimal;
        discountType: string | null;
        total: Decimal;
        paidAmount: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        placeOfSupply: string | null;
        buyerGstin: string | null;
        recipientAddress: string | null;
        reverseCharge: boolean;
        ewayBillNo: string | null;
        ewayBillGeneratedAt: Date | null;
        irn: string | null;
        irnGeneratedAt: Date | null;
        ackNo: string | null;
        ackDate: Date | null;
        qrCode: string | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
        invoiceDate: Date;
        dueDate: Date | null;
        paidAt: Date | null;
        notes: string | null;
        tags: string[];
        pdfObjectKey: string | null;
        pdfUrl: string | null;
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    }[];
} & {
    tenantId: string;
    id: string;
    notes: string | null;
    tags: string[];
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    name: string;
    phone: string | null;
    alternatePhone: string[];
    email: string | null;
    honorific: string | null;
    localName: string | null;
    nickname: string[];
    addressLine1: string | null;
    addressLine2: string | null;
    landmark: string | null;
    area: string | null;
    city: string | null;
    district: string | null;
    state: string | null;
    pincode: string | null;
    gstin: string | null;
    pan: string | null;
    businessType: string | null;
    creditLimit: Decimal;
    balance: Decimal;
    totalPurchases: Decimal;
    totalPayments: Decimal;
    lastPaymentAmount: Decimal | null;
    lastPaymentDate: Date | null;
    averagePaymentDays: number | null;
    loyaltyPoints: number;
    loyaltyTier: string;
    visitCount: number;
    firstVisit: Date | null;
    lastVisit: Date | null;
    averageBasketSize: Decimal | null;
    preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
    preferredTimeOfDay: Date | null;
    preferredDays: string[];
    frequencyScore: Decimal;
    recencyScore: Decimal;
    monetaryScore: Decimal;
    overallScore: Decimal | null;
    metadata: import("@prisma/client/runtime/library").JsonValue;
    voiceFingerprint: string | null;
    commonPhrases: string[];
    updatedBy: string | null;
}) | null>;
export declare function getCustomerBalance(customerId: string): Promise<number>;
export declare function searchCustomers(query: string): Promise<CustomerSearchResult[]>;
export declare function listCustomers(limit?: number): Promise<CustomerSearchResult[]>;
export declare function listOverdueCustomers(): Promise<{
    id: string;
    name: string;
    balance: number;
    landmark: string | undefined;
    phone: string | undefined;
}[]>;
export declare function getTotalPending(): Promise<number>;
export declare function getCustomerCommPrefs(customerId: string): Promise<{
    tenantId: string;
    id: string;
    customerId: string;
    createdAt: Date;
    updatedAt: Date;
    whatsappEnabled: boolean;
    whatsappNumber: string | null;
    whatsappOptInTime: Date | null;
    whatsappOptInIp: string | null;
    emailEnabled: boolean;
    emailAddress: string | null;
    emailVerified: boolean;
    emailVerifiedAt: Date | null;
    smsEnabled: boolean;
    smsNumber: string | null;
    preferredLanguage: string;
    preferredTime: Date | null;
    quietHours: import("@prisma/client/runtime/library").JsonValue;
    maxPerWeek: number;
    maxPerMonth: number;
    messagesSentThisWeek: number;
    messagesSentThisMonth: number;
    lastMessageAt: Date | null;
    consentGiven: boolean;
    consentDate: Date | null;
    consentSource: string | null;
    consentIp: string | null;
    optedOut: boolean;
    optedOutAt: Date | null;
    optOutReason: string | null;
} | null>;
export declare function createCustomer(data: {
    name: string;
    phone?: string;
    email?: string;
    nickname?: string;
    landmark?: string;
    notes?: string;
    openingBalance?: number;
    creditLimit?: number;
    tags?: string[];
    gstin?: string;
}): Promise<{
    tenantId: string;
    id: string;
    notes: string | null;
    tags: string[];
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    name: string;
    phone: string | null;
    alternatePhone: string[];
    email: string | null;
    honorific: string | null;
    localName: string | null;
    nickname: string[];
    addressLine1: string | null;
    addressLine2: string | null;
    landmark: string | null;
    area: string | null;
    city: string | null;
    district: string | null;
    state: string | null;
    pincode: string | null;
    gstin: string | null;
    pan: string | null;
    businessType: string | null;
    creditLimit: Decimal;
    balance: Decimal;
    totalPurchases: Decimal;
    totalPayments: Decimal;
    lastPaymentAmount: Decimal | null;
    lastPaymentDate: Date | null;
    averagePaymentDays: number | null;
    loyaltyPoints: number;
    loyaltyTier: string;
    visitCount: number;
    firstVisit: Date | null;
    lastVisit: Date | null;
    averageBasketSize: Decimal | null;
    preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
    preferredTimeOfDay: Date | null;
    preferredDays: string[];
    frequencyScore: Decimal;
    recencyScore: Decimal;
    monetaryScore: Decimal;
    overallScore: Decimal | null;
    metadata: import("@prisma/client/runtime/library").JsonValue;
    voiceFingerprint: string | null;
    commonPhrases: string[];
    updatedBy: string | null;
}>;
export declare function updateCustomer(id: string, data: {
    name?: string;
    phone?: string;
    email?: string;
    nickname?: string;
    landmark?: string;
    creditLimit?: number;
    tags?: string[];
    notes?: string;
    gstin?: string | null;
}): Promise<{
    tenantId: string;
    id: string;
    notes: string | null;
    tags: string[];
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    name: string;
    phone: string | null;
    alternatePhone: string[];
    email: string | null;
    honorific: string | null;
    localName: string | null;
    nickname: string[];
    addressLine1: string | null;
    addressLine2: string | null;
    landmark: string | null;
    area: string | null;
    city: string | null;
    district: string | null;
    state: string | null;
    pincode: string | null;
    gstin: string | null;
    pan: string | null;
    businessType: string | null;
    creditLimit: Decimal;
    balance: Decimal;
    totalPurchases: Decimal;
    totalPayments: Decimal;
    lastPaymentAmount: Decimal | null;
    lastPaymentDate: Date | null;
    averagePaymentDays: number | null;
    loyaltyPoints: number;
    loyaltyTier: string;
    visitCount: number;
    firstVisit: Date | null;
    lastVisit: Date | null;
    averageBasketSize: Decimal | null;
    preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
    preferredTimeOfDay: Date | null;
    preferredDays: string[];
    frequencyScore: Decimal;
    recencyScore: Decimal;
    monetaryScore: Decimal;
    overallScore: Decimal | null;
    metadata: import("@prisma/client/runtime/library").JsonValue;
    voiceFingerprint: string | null;
    commonPhrases: string[];
    updatedBy: string | null;
}>;
export declare function updateCustomerBalance(customerId: string, amount: number): Promise<{
    tenantId: string;
    id: string;
    notes: string | null;
    tags: string[];
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    name: string;
    phone: string | null;
    alternatePhone: string[];
    email: string | null;
    honorific: string | null;
    localName: string | null;
    nickname: string[];
    addressLine1: string | null;
    addressLine2: string | null;
    landmark: string | null;
    area: string | null;
    city: string | null;
    district: string | null;
    state: string | null;
    pincode: string | null;
    gstin: string | null;
    pan: string | null;
    businessType: string | null;
    creditLimit: Decimal;
    balance: Decimal;
    totalPurchases: Decimal;
    totalPayments: Decimal;
    lastPaymentAmount: Decimal | null;
    lastPaymentDate: Date | null;
    averagePaymentDays: number | null;
    loyaltyPoints: number;
    loyaltyTier: string;
    visitCount: number;
    firstVisit: Date | null;
    lastVisit: Date | null;
    averageBasketSize: Decimal | null;
    preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
    preferredTimeOfDay: Date | null;
    preferredDays: string[];
    frequencyScore: Decimal;
    recencyScore: Decimal;
    monetaryScore: Decimal;
    overallScore: Decimal | null;
    metadata: import("@prisma/client/runtime/library").JsonValue;
    voiceFingerprint: string | null;
    commonPhrases: string[];
    updatedBy: string | null;
}>;
export declare function upsertCustomerCommPrefs(customerId: string, data: {
    whatsappEnabled?: boolean;
    whatsappNumber?: string;
    emailEnabled?: boolean;
    emailAddress?: string;
    smsEnabled?: boolean;
    preferredLanguage?: string;
}): Promise<{
    tenantId: string;
    id: string;
    customerId: string;
    createdAt: Date;
    updatedAt: Date;
    whatsappEnabled: boolean;
    whatsappNumber: string | null;
    whatsappOptInTime: Date | null;
    whatsappOptInIp: string | null;
    emailEnabled: boolean;
    emailAddress: string | null;
    emailVerified: boolean;
    emailVerifiedAt: Date | null;
    smsEnabled: boolean;
    smsNumber: string | null;
    preferredLanguage: string;
    preferredTime: Date | null;
    quietHours: import("@prisma/client/runtime/library").JsonValue;
    maxPerWeek: number;
    maxPerMonth: number;
    messagesSentThisWeek: number;
    messagesSentThisMonth: number;
    lastMessageAt: Date | null;
    consentGiven: boolean;
    consentDate: Date | null;
    consentSource: string | null;
    consentIp: string | null;
    optedOut: boolean;
    optedOutAt: Date | null;
    optOutReason: string | null;
}>;
export declare function deleteCustomer(customerId: string): Promise<{
    success: boolean;
    deletedRecords: {
        invoices: number;
        payments: number;
        reminders: number;
        messageLogs: number;
        invoiceItems: number;
        customer: number;
    };
    error?: undefined;
} | {
    success: boolean;
    error: string;
    deletedRecords: {
        invoices: number;
        payments: number;
        reminders: number;
        messageLogs: number;
        invoiceItems: number;
        customer: number;
    };
}>;
//# sourceMappingURL=customer.d.ts.map