/**
 * reporting/finance-reports/profit-loss
 *
 * READ-ONLY. Month-wise revenue, tax collected, discounts, payments received.
 * Also item-wise P&L breakdown.
 * Source of truth: accounting/gst/gstr1.service.ts
 */
// P&L reports are generated by gstr1Service singleton methods
export type { PnlReport, PnlMonthEntry, ItemwisePnlEntry } from "../../../accounting/gst/gstr1.service";
export { gstr1Service } from "../../../accounting/gst/gstr1.service";
