/**
 * Sales domain — invoice business operations.
 *
 * Direct Prisma calls, flat async functions, no class wrappers.
 * Covers the full invoice lifecycle: create, preview/confirm (voice-flow),
 * proforma conversion, update, cancel, PDF dispatch, and reporting.
 *
 * Old class singleton (invoiceService) is preserved in modules/invoice/invoice.service.ts
 * for the voice engine which imports it via relative paths.
 */
import { InvoiceItemInput } from "@execora/types";
import { Decimal } from "@prisma/client/runtime/library";
import { type SupplyType } from "../modules/gst/gst.service";
import type { InvoiceOptions } from "../modules/invoice/invoice.service";
export type { InvoiceOptions };
/**
 * Preview invoice — resolves products, optionally calculates GST per line,
 * and returns fully priced items WITHOUT committing to DB.
 * Used by voice engine and proforma quoting.
 */
export declare function previewInvoice(customerId: string, items: InvoiceItemInput[], withGst?: boolean, supplyType?: SupplyType, discountPercent?: number): Promise<{
    grandTotal: number;
    discountAmt: number;
    discountType: string;
    autoCreatedProducts: string[];
    subtotal: number;
    totalCgst: number;
    totalSgst: number;
    totalIgst: number;
    totalCess: number;
    totalTax: number;
    supplyType: SupplyType;
    resolvedItems: {
        productId: string;
        productName: string;
        unit: string;
        hsnCode: string | null;
        quantity: number;
        unitPrice: number;
        gstRate: number;
        cessRate: number;
        isGstExempt: boolean;
        cgst: number;
        sgst: number;
        igst: number;
        cess: number;
        subtotal: number;
        totalTax: number;
        total: number;
        autoCreated: boolean;
    }[];
}>;
/**
 * Confirm invoice — creates DB record from already-resolved items (post-preview).
 * Call after user confirms the preview in voice or UI flow.
 */
export declare function confirmInvoice(customerId: string, resolvedItems: Array<{
    productId: string;
    productName: string;
    unit: string;
    hsnCode?: string | null;
    quantity: number;
    unitPrice: number;
    gstRate?: number;
    cessRate?: number;
    isGstExempt?: boolean;
    cgst?: number;
    sgst?: number;
    igst?: number;
    cess?: number;
    subtotal?: number;
    totalTax?: number;
    total: number;
}>, notes?: string, opts?: InvoiceOptions): Promise<{
    customer: {
        tenantId: string;
        balance: Decimal;
        creditLimit: Decimal;
        totalPurchases: Decimal;
        totalPayments: Decimal;
        lastPaymentAmount: Decimal | null;
        averagePaymentDays: number | null;
        loyaltyPoints: number;
        visitCount: number;
        averageBasketSize: Decimal | null;
        frequencyScore: Decimal;
        recencyScore: Decimal;
        monetaryScore: Decimal;
        overallScore: Decimal | null;
        id: string;
        name: string;
        phone: string | null;
        alternatePhone: string[];
        email: string | null;
        honorific: string | null;
        localName: string | null;
        nickname: string[];
        addressLine1: string | null;
        addressLine2: string | null;
        landmark: string | null;
        area: string | null;
        city: string | null;
        district: string | null;
        state: string | null;
        pincode: string | null;
        gstin: string | null;
        pan: string | null;
        businessType: string | null;
        lastPaymentDate: Date | null;
        loyaltyTier: string;
        firstVisit: Date | null;
        lastVisit: Date | null;
        preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
        preferredTimeOfDay: Date | null;
        preferredDays: string[];
        tags: string[];
        notes: string | null;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        voiceFingerprint: string | null;
        commonPhrases: string[];
        createdBy: string | null;
        updatedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    } | null;
    items: ({
        product: {
            tenantId: string;
            id: string;
            name: string;
            tags: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            cess: Decimal;
            description: string | null;
            isActive: boolean;
            unit: string;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            category: string;
            subCategory: string | null;
            sku: string | null;
            barcode: string | null;
            price: Decimal;
            cost: Decimal | null;
            wholesalePrice: Decimal | null;
            priceTier2: Decimal | null;
            priceTier3: Decimal | null;
            baseUnit: string | null;
            baseUnitQuantity: Decimal | null;
            stock: number;
            minStock: number;
            maxStock: number | null;
            location: string | null;
            isGstExempt: boolean;
            trackBatches: boolean;
            trackSerialNumbers: boolean;
            hasVariants: boolean;
            imageUrl: string | null;
            imageUrls: string[];
            preferredSupplier: string | null;
            supplierId: string | null;
            isFeatured: boolean;
            attributes: import("@prisma/client/runtime/library").JsonValue;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        serialNumbers: string[];
        subtotal: Decimal;
        discount: Decimal;
        total: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        invoiceId: string;
        productId: string | null;
        productName: string;
        variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
        quantity: Decimal;
        unit: string;
        unitPrice: Decimal;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        variantId: string | null;
        batchId: string | null;
    })[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
}>;
/**
 * Create invoice with atomic transaction — used by REST API (Form/Dashboard mode).
 */
export declare function createInvoice(customerId: string, items: InvoiceItemInput[], notes?: string, opts?: InvoiceOptions & {
    isProforma?: boolean;
}): Promise<{
    invoice: {
        customer: {
            tenantId: string;
            balance: Decimal;
            creditLimit: Decimal;
            totalPurchases: Decimal;
            totalPayments: Decimal;
            lastPaymentAmount: Decimal | null;
            averagePaymentDays: number | null;
            loyaltyPoints: number;
            visitCount: number;
            averageBasketSize: Decimal | null;
            frequencyScore: Decimal;
            recencyScore: Decimal;
            monetaryScore: Decimal;
            overallScore: Decimal | null;
            id: string;
            name: string;
            phone: string | null;
            alternatePhone: string[];
            email: string | null;
            honorific: string | null;
            localName: string | null;
            nickname: string[];
            addressLine1: string | null;
            addressLine2: string | null;
            landmark: string | null;
            area: string | null;
            city: string | null;
            district: string | null;
            state: string | null;
            pincode: string | null;
            gstin: string | null;
            pan: string | null;
            businessType: string | null;
            lastPaymentDate: Date | null;
            loyaltyTier: string;
            firstVisit: Date | null;
            lastVisit: Date | null;
            preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
            preferredTimeOfDay: Date | null;
            preferredDays: string[];
            tags: string[];
            notes: string | null;
            metadata: import("@prisma/client/runtime/library").JsonValue;
            voiceFingerprint: string | null;
            commonPhrases: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
        } | null;
        items: ({
            product: {
                tenantId: string;
                id: string;
                name: string;
                tags: string[];
                createdBy: string | null;
                updatedBy: string | null;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                cess: Decimal;
                description: string | null;
                isActive: boolean;
                unit: string;
                mrp: Decimal | null;
                hsnCode: string | null;
                gstRate: Decimal;
                category: string;
                subCategory: string | null;
                sku: string | null;
                barcode: string | null;
                price: Decimal;
                cost: Decimal | null;
                wholesalePrice: Decimal | null;
                priceTier2: Decimal | null;
                priceTier3: Decimal | null;
                baseUnit: string | null;
                baseUnitQuantity: Decimal | null;
                stock: number;
                minStock: number;
                maxStock: number | null;
                location: string | null;
                isGstExempt: boolean;
                trackBatches: boolean;
                trackSerialNumbers: boolean;
                hasVariants: boolean;
                imageUrl: string | null;
                imageUrls: string[];
                preferredSupplier: string | null;
                supplierId: string | null;
                isFeatured: boolean;
                attributes: import("@prisma/client/runtime/library").JsonValue;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            serialNumbers: string[];
            subtotal: Decimal;
            discount: Decimal;
            total: Decimal;
            tax: Decimal;
            cgst: Decimal;
            sgst: Decimal;
            igst: Decimal;
            cess: Decimal;
            invoiceId: string;
            productId: string | null;
            productName: string;
            variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
            quantity: Decimal;
            unit: string;
            unitPrice: Decimal;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            variantId: string | null;
            batchId: string | null;
        })[];
    } & {
        tenantId: string;
        id: string;
        tags: string[];
        notes: string | null;
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNo: string;
        customerId: string | null;
        subtotal: Decimal;
        discount: Decimal;
        discountType: string | null;
        total: Decimal;
        paidAmount: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        placeOfSupply: string | null;
        buyerGstin: string | null;
        recipientAddress: string | null;
        reverseCharge: boolean;
        ewayBillNo: string | null;
        ewayBillGeneratedAt: Date | null;
        irn: string | null;
        irnGeneratedAt: Date | null;
        ackNo: string | null;
        ackDate: Date | null;
        qrCode: string | null;
        paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
        invoiceDate: Date;
        dueDate: Date | null;
        paidAt: Date | null;
        pdfObjectKey: string | null;
        pdfUrl: string | null;
    };
    autoCreatedProducts: string[];
}>;
/**
 * Convert proforma → actual invoice.
 * Deducts stock and updates customer balance.
 */
export declare function convertProformaToInvoice(invoiceId: string, initialPayment?: {
    amount: number;
    method: "cash" | "upi" | "card" | "other";
}): Promise<{
    customer: {
        tenantId: string;
        balance: Decimal;
        creditLimit: Decimal;
        totalPurchases: Decimal;
        totalPayments: Decimal;
        lastPaymentAmount: Decimal | null;
        averagePaymentDays: number | null;
        loyaltyPoints: number;
        visitCount: number;
        averageBasketSize: Decimal | null;
        frequencyScore: Decimal;
        recencyScore: Decimal;
        monetaryScore: Decimal;
        overallScore: Decimal | null;
        id: string;
        name: string;
        phone: string | null;
        alternatePhone: string[];
        email: string | null;
        honorific: string | null;
        localName: string | null;
        nickname: string[];
        addressLine1: string | null;
        addressLine2: string | null;
        landmark: string | null;
        area: string | null;
        city: string | null;
        district: string | null;
        state: string | null;
        pincode: string | null;
        gstin: string | null;
        pan: string | null;
        businessType: string | null;
        lastPaymentDate: Date | null;
        loyaltyTier: string;
        firstVisit: Date | null;
        lastVisit: Date | null;
        preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
        preferredTimeOfDay: Date | null;
        preferredDays: string[];
        tags: string[];
        notes: string | null;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        voiceFingerprint: string | null;
        commonPhrases: string[];
        createdBy: string | null;
        updatedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    } | null;
    items: ({
        product: {
            tenantId: string;
            id: string;
            name: string;
            tags: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            cess: Decimal;
            description: string | null;
            isActive: boolean;
            unit: string;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            category: string;
            subCategory: string | null;
            sku: string | null;
            barcode: string | null;
            price: Decimal;
            cost: Decimal | null;
            wholesalePrice: Decimal | null;
            priceTier2: Decimal | null;
            priceTier3: Decimal | null;
            baseUnit: string | null;
            baseUnitQuantity: Decimal | null;
            stock: number;
            minStock: number;
            maxStock: number | null;
            location: string | null;
            isGstExempt: boolean;
            trackBatches: boolean;
            trackSerialNumbers: boolean;
            hasVariants: boolean;
            imageUrl: string | null;
            imageUrls: string[];
            preferredSupplier: string | null;
            supplierId: string | null;
            isFeatured: boolean;
            attributes: import("@prisma/client/runtime/library").JsonValue;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        serialNumbers: string[];
        subtotal: Decimal;
        discount: Decimal;
        total: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        invoiceId: string;
        productId: string | null;
        productName: string;
        variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
        quantity: Decimal;
        unit: string;
        unitPrice: Decimal;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        variantId: string | null;
        batchId: string | null;
    })[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
}>;
/**
 * Update a pending/draft invoice — re-resolves items, restores then re-deducts stock.
 */
export declare function updateInvoice(invoiceId: string, changes: {
    items?: InvoiceItemInput[];
    notes?: string;
    opts?: InvoiceOptions;
}): Promise<{
    customer: {
        tenantId: string;
        balance: Decimal;
        creditLimit: Decimal;
        totalPurchases: Decimal;
        totalPayments: Decimal;
        lastPaymentAmount: Decimal | null;
        averagePaymentDays: number | null;
        loyaltyPoints: number;
        visitCount: number;
        averageBasketSize: Decimal | null;
        frequencyScore: Decimal;
        recencyScore: Decimal;
        monetaryScore: Decimal;
        overallScore: Decimal | null;
        id: string;
        name: string;
        phone: string | null;
        alternatePhone: string[];
        email: string | null;
        honorific: string | null;
        localName: string | null;
        nickname: string[];
        addressLine1: string | null;
        addressLine2: string | null;
        landmark: string | null;
        area: string | null;
        city: string | null;
        district: string | null;
        state: string | null;
        pincode: string | null;
        gstin: string | null;
        pan: string | null;
        businessType: string | null;
        lastPaymentDate: Date | null;
        loyaltyTier: string;
        firstVisit: Date | null;
        lastVisit: Date | null;
        preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
        preferredTimeOfDay: Date | null;
        preferredDays: string[];
        tags: string[];
        notes: string | null;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        voiceFingerprint: string | null;
        commonPhrases: string[];
        createdBy: string | null;
        updatedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    } | null;
    items: ({
        product: {
            tenantId: string;
            id: string;
            name: string;
            tags: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            cess: Decimal;
            description: string | null;
            isActive: boolean;
            unit: string;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            category: string;
            subCategory: string | null;
            sku: string | null;
            barcode: string | null;
            price: Decimal;
            cost: Decimal | null;
            wholesalePrice: Decimal | null;
            priceTier2: Decimal | null;
            priceTier3: Decimal | null;
            baseUnit: string | null;
            baseUnitQuantity: Decimal | null;
            stock: number;
            minStock: number;
            maxStock: number | null;
            location: string | null;
            isGstExempt: boolean;
            trackBatches: boolean;
            trackSerialNumbers: boolean;
            hasVariants: boolean;
            imageUrl: string | null;
            imageUrls: string[];
            preferredSupplier: string | null;
            supplierId: string | null;
            isFeatured: boolean;
            attributes: import("@prisma/client/runtime/library").JsonValue;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        serialNumbers: string[];
        subtotal: Decimal;
        discount: Decimal;
        total: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        invoiceId: string;
        productId: string | null;
        productName: string;
        variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
        quantity: Decimal;
        unit: string;
        unitPrice: Decimal;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        variantId: string | null;
        batchId: string | null;
    })[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
}>;
/**
 * Cancel invoice — reverses stock and customer balance.
 */
export declare function cancelInvoice(invoiceId: string): Promise<{
    items: ({
        product: {
            tenantId: string;
            id: string;
            name: string;
            tags: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            cess: Decimal;
            description: string | null;
            isActive: boolean;
            unit: string;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            category: string;
            subCategory: string | null;
            sku: string | null;
            barcode: string | null;
            price: Decimal;
            cost: Decimal | null;
            wholesalePrice: Decimal | null;
            priceTier2: Decimal | null;
            priceTier3: Decimal | null;
            baseUnit: string | null;
            baseUnitQuantity: Decimal | null;
            stock: number;
            minStock: number;
            maxStock: number | null;
            location: string | null;
            isGstExempt: boolean;
            trackBatches: boolean;
            trackSerialNumbers: boolean;
            hasVariants: boolean;
            imageUrl: string | null;
            imageUrls: string[];
            preferredSupplier: string | null;
            supplierId: string | null;
            isFeatured: boolean;
            attributes: import("@prisma/client/runtime/library").JsonValue;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        serialNumbers: string[];
        subtotal: Decimal;
        discount: Decimal;
        total: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        invoiceId: string;
        productId: string | null;
        productName: string;
        variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
        quantity: Decimal;
        unit: string;
        unitPrice: Decimal;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        variantId: string | null;
        batchId: string | null;
    })[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
}>;
/**
 * Persist the MinIO object key (and presigned URL) on an invoice record.
 */
export declare function savePdfUrl(invoiceId: string, pdfObjectKey: string, pdfUrl: string): Promise<void>;
/**
 * Generate invoice PDF, upload to MinIO, and send via email / WhatsApp.
 * Non-fatal — never blocks the invoice flow. Call fire-and-forget.
 */
export declare function dispatchInvoicePdfEmail(invoiceId: string): Promise<void>;
export declare function getInvoiceById(invoiceId: string): Promise<({
    customer: {
        tenantId: string;
        balance: Decimal;
        creditLimit: Decimal;
        totalPurchases: Decimal;
        totalPayments: Decimal;
        lastPaymentAmount: Decimal | null;
        averagePaymentDays: number | null;
        loyaltyPoints: number;
        visitCount: number;
        averageBasketSize: Decimal | null;
        frequencyScore: Decimal;
        recencyScore: Decimal;
        monetaryScore: Decimal;
        overallScore: Decimal | null;
        id: string;
        name: string;
        phone: string | null;
        alternatePhone: string[];
        email: string | null;
        honorific: string | null;
        localName: string | null;
        nickname: string[];
        addressLine1: string | null;
        addressLine2: string | null;
        landmark: string | null;
        area: string | null;
        city: string | null;
        district: string | null;
        state: string | null;
        pincode: string | null;
        gstin: string | null;
        pan: string | null;
        businessType: string | null;
        lastPaymentDate: Date | null;
        loyaltyTier: string;
        firstVisit: Date | null;
        lastVisit: Date | null;
        preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
        preferredTimeOfDay: Date | null;
        preferredDays: string[];
        tags: string[];
        notes: string | null;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        voiceFingerprint: string | null;
        commonPhrases: string[];
        createdBy: string | null;
        updatedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    } | null;
    items: ({
        product: {
            tenantId: string;
            id: string;
            name: string;
            tags: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            cess: Decimal;
            description: string | null;
            isActive: boolean;
            unit: string;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            category: string;
            subCategory: string | null;
            sku: string | null;
            barcode: string | null;
            price: Decimal;
            cost: Decimal | null;
            wholesalePrice: Decimal | null;
            priceTier2: Decimal | null;
            priceTier3: Decimal | null;
            baseUnit: string | null;
            baseUnitQuantity: Decimal | null;
            stock: number;
            minStock: number;
            maxStock: number | null;
            location: string | null;
            isGstExempt: boolean;
            trackBatches: boolean;
            trackSerialNumbers: boolean;
            hasVariants: boolean;
            imageUrl: string | null;
            imageUrls: string[];
            preferredSupplier: string | null;
            supplierId: string | null;
            isFeatured: boolean;
            attributes: import("@prisma/client/runtime/library").JsonValue;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        serialNumbers: string[];
        subtotal: Decimal;
        discount: Decimal;
        total: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        invoiceId: string;
        productId: string | null;
        productName: string;
        variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
        quantity: Decimal;
        unit: string;
        unitPrice: Decimal;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        variantId: string | null;
        batchId: string | null;
    })[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
}) | null>;
export declare function getRecentInvoices(limit?: number): Promise<({
    customer: {
        tenantId: string;
        balance: Decimal;
        creditLimit: Decimal;
        totalPurchases: Decimal;
        totalPayments: Decimal;
        lastPaymentAmount: Decimal | null;
        averagePaymentDays: number | null;
        loyaltyPoints: number;
        visitCount: number;
        averageBasketSize: Decimal | null;
        frequencyScore: Decimal;
        recencyScore: Decimal;
        monetaryScore: Decimal;
        overallScore: Decimal | null;
        id: string;
        name: string;
        phone: string | null;
        alternatePhone: string[];
        email: string | null;
        honorific: string | null;
        localName: string | null;
        nickname: string[];
        addressLine1: string | null;
        addressLine2: string | null;
        landmark: string | null;
        area: string | null;
        city: string | null;
        district: string | null;
        state: string | null;
        pincode: string | null;
        gstin: string | null;
        pan: string | null;
        businessType: string | null;
        lastPaymentDate: Date | null;
        loyaltyTier: string;
        firstVisit: Date | null;
        lastVisit: Date | null;
        preferredPaymentMethod: import(".prisma/client").$Enums.PaymentMethod[];
        preferredTimeOfDay: Date | null;
        preferredDays: string[];
        tags: string[];
        notes: string | null;
        metadata: import("@prisma/client/runtime/library").JsonValue;
        voiceFingerprint: string | null;
        commonPhrases: string[];
        createdBy: string | null;
        updatedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    } | null;
    items: ({
        product: {
            tenantId: string;
            id: string;
            name: string;
            tags: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            cess: Decimal;
            description: string | null;
            isActive: boolean;
            unit: string;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            category: string;
            subCategory: string | null;
            sku: string | null;
            barcode: string | null;
            price: Decimal;
            cost: Decimal | null;
            wholesalePrice: Decimal | null;
            priceTier2: Decimal | null;
            priceTier3: Decimal | null;
            baseUnit: string | null;
            baseUnitQuantity: Decimal | null;
            stock: number;
            minStock: number;
            maxStock: number | null;
            location: string | null;
            isGstExempt: boolean;
            trackBatches: boolean;
            trackSerialNumbers: boolean;
            hasVariants: boolean;
            imageUrl: string | null;
            imageUrls: string[];
            preferredSupplier: string | null;
            supplierId: string | null;
            isFeatured: boolean;
            attributes: import("@prisma/client/runtime/library").JsonValue;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        serialNumbers: string[];
        subtotal: Decimal;
        discount: Decimal;
        total: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        invoiceId: string;
        productId: string | null;
        productName: string;
        variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
        quantity: Decimal;
        unit: string;
        unitPrice: Decimal;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        variantId: string | null;
        batchId: string | null;
    })[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
})[]>;
export declare function getCustomerInvoices(customerId: string, limit?: number): Promise<({
    items: ({
        product: {
            tenantId: string;
            id: string;
            name: string;
            tags: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            cess: Decimal;
            description: string | null;
            isActive: boolean;
            unit: string;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            category: string;
            subCategory: string | null;
            sku: string | null;
            barcode: string | null;
            price: Decimal;
            cost: Decimal | null;
            wholesalePrice: Decimal | null;
            priceTier2: Decimal | null;
            priceTier3: Decimal | null;
            baseUnit: string | null;
            baseUnitQuantity: Decimal | null;
            stock: number;
            minStock: number;
            maxStock: number | null;
            location: string | null;
            isGstExempt: boolean;
            trackBatches: boolean;
            trackSerialNumbers: boolean;
            hasVariants: boolean;
            imageUrl: string | null;
            imageUrls: string[];
            preferredSupplier: string | null;
            supplierId: string | null;
            isFeatured: boolean;
            attributes: import("@prisma/client/runtime/library").JsonValue;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        serialNumbers: string[];
        subtotal: Decimal;
        discount: Decimal;
        total: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        invoiceId: string;
        productId: string | null;
        productName: string;
        variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
        quantity: Decimal;
        unit: string;
        unitPrice: Decimal;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        variantId: string | null;
        batchId: string | null;
    })[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
})[]>;
export declare function getLastInvoice(customerId: string): Promise<({
    items: ({
        product: {
            tenantId: string;
            id: string;
            name: string;
            tags: string[];
            createdBy: string | null;
            updatedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            cess: Decimal;
            description: string | null;
            isActive: boolean;
            unit: string;
            mrp: Decimal | null;
            hsnCode: string | null;
            gstRate: Decimal;
            category: string;
            subCategory: string | null;
            sku: string | null;
            barcode: string | null;
            price: Decimal;
            cost: Decimal | null;
            wholesalePrice: Decimal | null;
            priceTier2: Decimal | null;
            priceTier3: Decimal | null;
            baseUnit: string | null;
            baseUnitQuantity: Decimal | null;
            stock: number;
            minStock: number;
            maxStock: number | null;
            location: string | null;
            isGstExempt: boolean;
            trackBatches: boolean;
            trackSerialNumbers: boolean;
            hasVariants: boolean;
            imageUrl: string | null;
            imageUrls: string[];
            preferredSupplier: string | null;
            supplierId: string | null;
            isFeatured: boolean;
            attributes: import("@prisma/client/runtime/library").JsonValue;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        serialNumbers: string[];
        subtotal: Decimal;
        discount: Decimal;
        total: Decimal;
        tax: Decimal;
        cgst: Decimal;
        sgst: Decimal;
        igst: Decimal;
        cess: Decimal;
        invoiceId: string;
        productId: string | null;
        productName: string;
        variantAttributes: import("@prisma/client/runtime/library").JsonValue | null;
        quantity: Decimal;
        unit: string;
        unitPrice: Decimal;
        mrp: Decimal | null;
        hsnCode: string | null;
        gstRate: Decimal;
        variantId: string | null;
        batchId: string | null;
    })[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
}) | null>;
export declare function getLastOrder(customerId: string): Promise<({
    items: {
        productName: string;
        quantity: Decimal;
        unitPrice: Decimal;
    }[];
} & {
    tenantId: string;
    id: string;
    tags: string[];
    notes: string | null;
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    status: import(".prisma/client").$Enums.InvoiceStatus;
    invoiceNo: string;
    customerId: string | null;
    subtotal: Decimal;
    discount: Decimal;
    discountType: string | null;
    total: Decimal;
    paidAmount: Decimal;
    tax: Decimal;
    cgst: Decimal;
    sgst: Decimal;
    igst: Decimal;
    cess: Decimal;
    placeOfSupply: string | null;
    buyerGstin: string | null;
    recipientAddress: string | null;
    reverseCharge: boolean;
    ewayBillNo: string | null;
    ewayBillGeneratedAt: Date | null;
    irn: string | null;
    irnGeneratedAt: Date | null;
    ackNo: string | null;
    ackDate: Date | null;
    qrCode: string | null;
    paymentMethod: import(".prisma/client").$Enums.PaymentMethod | null;
    invoiceDate: Date;
    dueDate: Date | null;
    paidAt: Date | null;
    pdfObjectKey: string | null;
    pdfUrl: string | null;
}) | null>;
export declare function getTopSelling(limit?: number, days?: number): Promise<{
    productId: string;
    productName: string;
    unit: string;
    category: string;
    price: string;
    stock: number;
    soldQty: number;
}[]>;
export declare function getSummaryRange(from: Date, to: Date): Promise<{
    from: string;
    to: string;
    invoiceCount: number;
    totalSales: number;
    totalPayments: number;
    cashPayments: number;
    upiPayments: number;
    pendingAmount: number;
    extraPayments: number;
}>;
export declare function getDailySummary(date?: Date): Promise<{
    date: Date;
    invoiceCount: number;
    totalSales: number;
    totalPayments: number;
    cashPayments: number;
    upiPayments: number;
    pendingAmount: number;
    extraPayments: number;
}>;
//# sourceMappingURL=invoice.d.ts.map