/**
 * sync-ip.mjs
 *
 * Detects the current LAN IP and writes EXPO_PUBLIC_API_URL into
 * apps/mobile/.env so the mobile app always points at the right machine —
 * no manual edits needed after network changes.
 *
 * Usage:
 *   node scripts/sync-ip.mjs          # auto-detect en0 / en1 / eth0
 *   EXPO_IP=192.168.x.x node scripts/sync-ip.mjs  # override
 *
 * Also called automatically via the "predev" npm hook.
 */

import { networkInterfaces } from 'os';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const MOBILE_ENV = resolve(ROOT, 'apps/mobile/.env');
const PORT = process.env.API_PORT ?? '3006';

// ── 1. Detect LAN IP ─────────────────────────────────────────────────────────

function detectLanIp() {
  // Allow manual override
  if (process.env.EXPO_IP) return process.env.EXPO_IP.trim();

  const ifaces = networkInterfaces();
  // Prefer common Wi-Fi interface names first
  const preferred = ['en0', 'en1', 'wlan0', 'wlo1', 'eth0'];

  for (const iface of preferred) {
    const addrs = ifaces[iface];
    if (!addrs) continue;
    for (const a of addrs) {
      if (a.family === 'IPv4' && !a.internal) return a.address;
    }
  }

  // Fallback: first non-internal IPv4 on any interface
  for (const addrs of Object.values(ifaces)) {
    for (const a of addrs ?? []) {
      if (a.family === 'IPv4' && !a.internal) return a.address;
    }
  }

  return null;
}

// ── 2. Update apps/mobile/.env ───────────────────────────────────────────────

function updateMobileEnv(ip) {
  const url = `http://${ip}:${PORT}`;

  if (!existsSync(MOBILE_ENV)) {
    const content = [
      '# Auto-generated by scripts/sync-ip.mjs — do not edit EXPO_PUBLIC_API_URL manually',
      `EXPO_PUBLIC_API_URL=${url}`,
      `EXPO_PUBLIC_LOGIN_EMAIL=bharatveeryadavg@gmail.com`,
      `EXPO_PUBLIC_LOGIN_PASSWORD=Owner@2024`,
    ].join('\n') + '\n';
    writeFileSync(MOBILE_ENV, content);
    console.log(`[sync-ip] Created apps/mobile/.env — API URL: ${url}`);
    return;
  }

  let content = readFileSync(MOBILE_ENV, 'utf8');
  const line = `EXPO_PUBLIC_API_URL=${url}`;

  if (content.includes('EXPO_PUBLIC_API_URL=')) {
    const before = content;
    content = content.replace(/EXPO_PUBLIC_API_URL=.*/g, line);
    if (content === before) {
      console.log(`[sync-ip] Already up-to-date: ${url}`);
    } else {
      writeFileSync(MOBILE_ENV, content);
      console.log(`[sync-ip] Updated API URL → ${url}`);
    }
  } else {
    writeFileSync(MOBILE_ENV, content.trimEnd() + '\n' + line + '\n');
    console.log(`[sync-ip] Added API URL → ${url}`);
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────

const ip = detectLanIp();

if (!ip) {
  console.warn('[sync-ip] Could not detect a LAN IP. Mobile app may not reach the API.');
  console.warn('         Set EXPO_IP=<your-ip> to override.');
  process.exit(0); // non-fatal — don't break the dev server start
}

updateMobileEnv(ip);
